# Generated by Django 3.2 on 2022-05-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw_heat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
